[tool.poetry]
name = "cg"
version = "0.1.0"
description = ""
authors = ["scc <scc@teamt5.org>"]
license = "GPL3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
