name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Setup Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Check format
      run: |
        poetry run autopep8 --in-place --aggressive --recursive .
        git diff --exit-code
      
    - name: Check lint (windows)
      if: matrix.os == 'windows-latest'
      run: |
        ci/check_lint/windows.ps1

    - name: Check lint (unix)
      if: matrix.os != 'windows-latest'
      run: |
        ci/check_lint/unix.sh

    - name: Build with Nuitka (windows)
      if: matrix.os == 'windows-latest'
      run: |
        ci/build_nuitka/windows.ps1
    - name: Build with Nuitka (unix)
      if: matrix.os != 'windows-latest'
      run: |
        ci/build_nuitka/unix.sh

    - name: Upload Artifact elf
      uses: actions/upload-artifact@v2
      with:
        name: cg.elf
        path: cg.elf

    - name: Upload Artifact exe
      uses: actions/upload-artifact@v2
      with:
        name: cg.exe
        path: cg.exe

    - name: Upload Artifact macho
      uses: actions/upload-artifact@v2
      with:
        name: cg.macho
        path: cg.macho

  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release Tag
      if: startsWith(github.ref, 'refs/heads/')
      run: |
        git config --local user.email "ci@scc-net.tw"
        git config --local user.name "CI"
        git tag "${{ github.run_id }}-${{ github.sha }}"
        git push origin --tags
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}


    - name: Download cg.elf artifact
      uses: actions/download-artifact@v2
      with:
        name: cg.elf
        path: cg.elf

    - name: Download cg.exe artifact
      uses: actions/download-artifact@v2
      with:
        name: cg.exe
        path: cg.exe

    - name: Download cg.macho artifact
      uses: actions/download-artifact@v2
      with:
        name: cg.macho
        path: cg.macho

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          cg.elf
          cg.exe
          cg.macho
        tag_name: ${{ github.ref }}
        body: |
          Release ${{ github.ref }}
        draft: false
        prerelease: false
        token: ${{ secrets.DEPLOY_TOKEN }}

