name: CI

on:
  push:
    branches-ignore:
      - release

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Setup Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Check format
      run: |
        poetry run autopep8 --in-place --aggressive --recursive .
        git diff --exit-code
      
    - name: Check lint (windows)
      if: matrix.os == 'windows-latest'
      run: |
        ci/check_lint/windows.ps1

    - name: Check lint (unix)
      if: matrix.os != 'windows-latest'
      run: |
        ci/check_lint/unix.sh
